# Generated by Django 4.1.6 on 2023-02-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yummo', '0002_rename_reservations_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='avg_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
