# Generated by Django 4.1.7 on 2023-03-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantAPI', '0003_alter_review_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisineID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='RestaurantAPI.cuisine'),
        ),
    ]
