# Generated by Django 4.1.7 on 2023-03-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantAPI', '0005_restaurant_contact_no_restaurant_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='location',
            new_name='address',
        ),
    ]
