# Generated by Django 4.1.7 on 2023-03-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantAPI', '0006_rename_location_restaurant_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.ManyToManyField(default=9, related_name='restaurants', to='RestaurantAPI.cuisine'),
        ),
    ]
