# Generated by Django 4.1.7 on 2023-03-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantAPI', '0007_alter_restaurant_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.ManyToManyField(blank=True, default=9, related_name='restaurants', to='RestaurantAPI.cuisine'),
        ),
    ]
