# Generated by Django 4.1.7 on 2023-03-23 07:42

from django.db import migrations
from ..models import Restaurant, Cuisine

def apply_default_cuisine(apps, schema_editor):
    # Get the default cuisine instance
    default_cuisine = Cuisine.objects.get_or_create(name='Asian')[0]

    # Get all Restaurant instances without a cuisine
    restaurants_without_cuisine = Restaurant.objects.filter(cuisine=None)

    # Assign the default cuisine to each Restaurant instance
    for restaurant in restaurants_without_cuisine:
        restaurant.cuisine.add(default_cuisine)

class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantAPI', '0008_alter_restaurant_cuisine'),
    ]

    operations = [
        migrations.RunPython(apply_default_cuisine)
    ]
