# Generated by Django 4.1.7 on 2023-04-01 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantAPI', '0011_add_lat_lng_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
