# Generated by Django 4.1.7 on 2023-04-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantAPI', '0013_alter_restaurant_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(blank=True, default='images/restaurant/default-restaurant-icon2.jpg', null=True, upload_to='images/restaurant'),
        ),
    ]
