# Generated by Django 4.1.7 on 2023-03-09 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YummoGroupAPI', '0004_customerprofile_merchantprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yummogroup',
            name='customers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Customers'}, related_name='yummogroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
