# Generated by Django 4.1.7 on 2023-04-01 14:26
from django.db import migrations
from django.core.files import File
from django.conf import settings
from ..models import CustomerProfile, MerchantProfile


def set_default_profile_icon(apps, schema_editor):
    # Get the default image file
    default_image_path = settings.MEDIA_ROOT + "/images/default-user-icon.jpg"
    default_image_file = open(default_image_path, 'rb')
    default_image = File(default_image_file)
    
    for profile in CustomerProfile.objects.all():
        if not profile.icon:
            profile.icon.save('default-user-icon.jpg', default_image, save=True)

    for profile in MerchantProfile.objects.all():
        if not profile.icon:
            profile.icon.save('default-user-icon.jpg', default_image, save=True)

class Migration(migrations.Migration):

    dependencies = [
        ('YummoGroupAPI', '0009_alter_customerprofile_icon_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_profile_icon),
    ]
